# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 42f69e38c977b6c2f1c1557716da26cc3d3575519d46756905dd1809ff809175e28d44abb2b336fe1a7af36b4c031b1cfc22dca94793f35303c49db054e25310

test:
  secret_key_base: 70e141a6048cf3f39f88450fdd9dd507393426b5a89d5d9f7f7b8c957ee2084f4456c9d62e834d59b3fe4064642fb607fa1a5535fa2ee1ebf9bea9e6b35e2d86

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
